# Generated by Django 5.0.7 on 2024-07-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0003_reservation_reservation_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="modified",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
