# Generated by Django 5.0.7 on 2024-07-16 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0004_alter_reservation_created_alter_reservation_modified"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reservation",
            old_name="total_cost",
            new_name="ticket_cost",
        ),
    ]
