# Generated by Django 5.0.7 on 2024-07-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0005_rename_total_cost_reservation_ticket_cost"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="notification_send",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                choices=[
                    ("Active", "Active"),
                    ("Cancelled", "Cancelled"),
                    ("Expired", "Expired"),
                ],
                default="Active",
                max_length=255,
            ),
        ),
    ]
