# Generated by Django 5.0.7 on 2024-07-16 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0007_alter_reservation_seat"),
        ("ticketing", "0014_alter_show_theater"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="show",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="showreservations",
                to="ticketing.show",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customerreservations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
