# Generated by Django 5.0.7 on 2024-07-23 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0010_alter_reservation_created_alter_reservation_modified"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MovieTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "ticket_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=100),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Cancelled", "Cancelled"),
                            ("Expired", "Expired"),
                        ],
                        default="Active",
                        max_length=255,
                    ),
                ),
                (
                    "reservation_type",
                    models.CharField(
                        choices=[
                            ("Single Ticket", "Single Ticket"),
                            ("Multi Ticket", "Multi Ticket"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("notification_send", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="reservation",
            name="ticket",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="reservations.movieticket",
            ),
        ),
    ]
