# Generated by Django 5.0.7 on 2024-07-23 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0011_movieticket_reservation_ticket"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="ticket",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ticketreservations",
                to="reservations.movieticket",
            ),
        ),
    ]
