# Generated by Django 5.0.7 on 2024-07-23 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0012_alter_reservation_ticket"),
        ("ticketing", "0018_show_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="movieticket",
            name="show",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="showtickets",
                to="ticketing.show",
            ),
        ),
    ]
