version: '3.8'

services:
  web:
    build: .
    container_name: django_web
    command: gunicorn ShowTicketing.wsgi:application --bind 0.0.0.0:8000 --workers 3
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost
      - POSTGRES_DB=ticketing
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - DATABASE_HOST=postgres_db
      - CELERY_BROKER_URL=redis://localhost:6379/1
      - CELERY_RESULT_BACKEND=redis://localhost:6379/1
    depends_on:
      - db
      - redis

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      - POSTGRES_DB=ticketing
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis/redis-stack:latest
    container_name: redis_stack
    ports:
      - "6379:6379"
      - "8001:8001"  # Expose the web UI port
    environment:
      - REDIS_ARGS=--port 6379 --loadmodule /usr/lib/redis/modules/redisearch.so --loadmodule /usr/lib/redis/modules/redistimeseries.so --loadmodule /usr/lib/redis/modules/redisgraph.so --loadmodule /usr/lib/redis/modules/rejson.so --loadmodule /usr/lib/redis/modules/redisbloom.so --loadmodule /usr/lib/redis/modules/redisai.so --loadmodule /usr/lib/redis/modules/redistimeseries.so --loadmodule /usr/lib/redis/modules/redisgears.so
      - HTTP_PORT=8001  # Set the web UI port

  celery:
    build: .
    container_name: celery_worker
    command: celery -A ShowTicketing worker --loglevel=info
    volumes:
      - .:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
    depends_on:
      - db
      - redis
  

  celery-beat:
    build: .
    container_name: celery_beat
    command: celery -A ShowTicketing beat --loglevel=info
    volumes:
      - .:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
