version: '3.8'

services:
  web:
    build: .
    container_name: django_web
    command: gunicorn ShowTicketing.wsgi:application --bind 0.0.0.0:8000 --workers 3
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost
      - POSTGRES_DB=ticketing
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - DATABASE_HOST=db
      - CELERY_BROKER_URL=redis://34.123.255.211:6379/0
      - CELERY_RESULT_BACKEND=redis://34.123.255.211:6379/0
      - EMAIL_HOST=mailhog
      - EMAIL_PORT=1025
      - SITE_EMAIL=info@ticketing.com
      - EMAIL_HOST_PASSWORD=mailhog
      - EMAIL_HOST_USER=mailhog
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      - POSTGRES_DB=ticketing
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    volumes:
      - postgres_data:/var/lib/postgresql/data
      


  celery:
    build: .
    container_name: celery_worker
    command: celery -A ShowTicketing worker --loglevel=info
    volumes:
      - .:/app
    environment:
      - CELERY_BROKER_URL=redis://34.123.255.211:6379/0
      - CELERY_RESULT_BACKEND=redis://34.123.255.211:6379/0
    depends_on:
      - db
  

  celery-beat:
    build: .
    container_name: celery_beat
    command: celery -A ShowTicketing beat --loglevel=info
    volumes:
      - .:/app
    environment:
      - CELERY_BROKER_URL=redis://34.123.255.211:6379/0
      - CELERY_RESULT_BACKEND=redis://34.123.255.211:6379/0
    depends_on:
      - db

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    depends_on:
      - db 
      - web
      - celery
      - celery-beat
    
volumes:
  postgres_data:
