# Generated by Django 5.0.7 on 2024-07-15 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticketing", "0002_rename_theatre_theater_seating_reservation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="seat_number",
        ),
        migrations.AddField(
            model_name="reservation",
            name="seat_numbers",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="theater",
            name="number_of_rows",
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name="TheaterSeat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("seat_number", models.CharField(max_length=10)),
                ("booked", models.BooleanField(default=False)),
                (
                    "theater",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ticketing.theater",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
