# Generated by Django 5.0.7 on 2024-07-15 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticketing", "0003_remove_reservation_seat_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="seating",
            name="charge_per_person",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
