# Generated by Django 5.0.7 on 2024-07-15 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticketing", "0004_seating_charge_per_person"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="seating",
            name="theater",
        ),
        migrations.RemoveField(
            model_name="theater",
            name="number_of_rows",
        ),
        migrations.AddField(
            model_name="reservation",
            name="total_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.CreateModel(
            name="Show",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, null=True)),
                (
                    "charge_per_person",
                    models.DecimalField(decimal_places=2, default=0, max_digits=100),
                ),
                ("date", models.DateField()),
                ("show_time", models.TimeField()),
                (
                    "theater",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ticketing.theater",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="reservation",
            name="seating",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ticketing.show"
            ),
        ),
        migrations.CreateModel(
            name="TheaterSeating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("seat_number", models.CharField(max_length=10)),
                ("booked", models.BooleanField(default=False)),
                ("seating_date", models.DateField(null=True)),
                (
                    "show",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ticketing.show",
                    ),
                ),
                (
                    "theater",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ticketing.theater",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="TheaterSeat",
        ),
        migrations.DeleteModel(
            name="Seating",
        ),
    ]
