# Generated by Django 5.0.7 on 2024-07-15 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ticketing",
            "0005_remove_seating_theater_remove_theater_number_of_rows_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="reservation",
            old_name="seating",
            new_name="show",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="seat_numbers",
        ),
        migrations.AddField(
            model_name="reservation",
            name="seat",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ticketing.theaterseating",
            ),
        ),
    ]
