# Generated by Django 5.0.7 on 2024-07-15 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticketing", "0006_rename_seating_reservation_show_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="seat",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                to="ticketing.theaterseating",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="show",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="ticketing.show"
            ),
        ),
        migrations.AlterField(
            model_name="show",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="theaterseating",
            name="show",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ticketing.show"
            ),
        ),
        migrations.AlterField(
            model_name="theaterseating",
            name="theater",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="ticketing.theater"
            ),
        ),
    ]
