# Generated by Django 5.0.7 on 2024-07-15 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ticketing", "0007_alter_reservation_seat_alter_reservation_show_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="show",
            old_name="charge_per_person",
            new_name="ticket_cost",
        ),
    ]
