# Generated by Django 5.0.7 on 2024-07-16 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticketing", "0009_delete_reservation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="theater",
            name="number_of_seats",
            field=models.IntegerField(),
        ),
    ]
