# Generated by Django 5.0.7 on 2024-07-16 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticketing", "0010_alter_theater_number_of_seats"),
    ]

    operations = [
        migrations.AlterField(
            model_name="show",
            name="ticket_cost",
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
