# Generated by Django 5.0.7 on 2024-07-16 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticketing", "0011_alter_show_ticket_cost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="theater",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="theater",
            name="modified",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="theaterseating",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="theaterseating",
            name="modified",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
