# Generated by Django 5.0.7 on 2024-07-16 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticketing", "0013_alter_theater_created_alter_theater_modified_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="show",
            name="theater",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="theatershows",
                to="ticketing.theater",
            ),
        ),
    ]
