# Generated by Django 5.0.7 on 2024-07-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticketing", "0017_alter_show_created_alter_show_modified_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="show",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
