# Generated by Django 5.0.7 on 2024-07-17 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="modified",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
